### ISSUE TITLE
npm WARN deprecated left-pad

### ISSUE THREAD

**Issue by manuzhang** [Atry/scalajs-all-in-one-template#9]
```
[error] npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
```

**Comment by Atry** [comment]
We may switch to [pad](https://github.com/adaltas/node-pad) instead of `left-pad`. Unfortunately the type definition for `pad` is incorrect (https://github.com/oyvindberg/ScalablyTyped/blob/master/p/pad/src/main/scala/typings/padLib/padMod.scala#L8), as it should be imported as `default`.

I think we can switch to `pad` once https://github.com/adaltas/node-pad/pull/16 is included in NPM and ScalablyTyped.

**Comment by Atry** [comment]
We can also use pad 2.x, which does not need https://github.com/adaltas/node-pad/pull/16
